---
- name: update application
  hosts: all
  gather_facts: false
  become: yes

  collections:
    - kubernetes.core
  
  tasks:
  - name: update all site
    include_role:
      name: website
      tasks_from: copy_site
    