---
- name: Update container
  hosts: all
  ignore_unreachable: yes
  gather_facts: false
  become: yes

  collections:
    - kubernetes.core
  
  tasks:
  - name: Delete All pod from namespace
    ansible.builtin.command: kubectl delete --all pods -n {{ item }}
    loop: "{{ ns_list }}"
    ignore_errors: yes
    ignore_unreachable: yes
    async: 120
    poll: 0