- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: "{{ client }}-nginx-vhost"
        namespace: "{{ client }}-system"
      data:
        nginx.conf: |
          server {
                 listen 80;
                 server_name {{ client }}.gsw.faire-savoir.eu;

                 location / {
                    root /usr/share/nginx/html/{{ client }}/www;
                    index index.html index.htm index.php;
                    try_files $uri $uri/ $uri.html $uri.php =404; 
                  }

                  location ~ /\. {
                    deny all;
                    access_log off;
                    log_not_found off;
                  }

                   error_log /var/log/error.log; 
                   access_log /var/log/acess.log; 
                   error_page 404 500 501 /error.php;
          }