- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ ns }}-service"
        namespace: "{{ ns }}"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
      spec:
        tls:
        - hosts: 
          - "{{ ndd }}"
          secretName: "{{ ndd }}-tls-credential"
        rules:
        - host: "{{ ndd }}"
          http:
            paths:
            - pathType: Prefix #Exact
              path: "/"
              backend:
                service:
                  name: "{{ ns }}-service"
                  port:
                    number: 80