- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ client }}-service"
        namespace: "{{ client }}-system"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
      spec:
        tls:
        - hosts: "{{ client }}.gsw.faire-savoir.eu"
          secretName: "{{ client }}-tls-credential"
        rules:
        - host: "{{ client }}.gsw.faire-savoir.eu"
          http:
            paths:
            - pathType: Prefix #Exact
              path: "/"
              backend:
                service:
                  name: "{{ client }}-service"
                  port:
                    number: 80