- name: Create a k8s configmap for nginx
  k8s:
    kubeconfig: /root/.kube/config
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: "{{ client }}-nginx-config"
        namespace: "{{ client }}-system"
      data:
        nginx.conf: |
          user  nginx;
          worker_processes  auto;

          error_log  /var/log/nginx/error.log notice;
          pid        /var/run/nginx.pid;
      
          events {
              worker_connections  1024;
          }

          http {
            server {
              listen 80 default_server;
              listen [::]:80 default_server;
              
              # Set nginx to serve files from the shared volume!
              root {{ defaultRootPath }};
              server_name _;
              
              #Set secure parameters
              server_tokens off;
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options nosniff;
              add_header X-XSS-Protection "1; mode=block";
              add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

              location / {
                #try_files $uri $uri.php$is_args$args;
                try_files $uri $uri/ $uri.html $uri.php$is_args$query_string;
              }
              location ~ \.css {
                add_header  Content-Type    text/css;
              }
              location ~ \.js {
                add_header  Content-Type    application/x-javascript;
              }
              location ~ \.php$ {
                include fastcgi_params;
                fastcgi_param REQUEST_METHOD $request_method;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_hide_header X-Powered-By;
              }
            }
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;
      
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;

              sendfile        on;
              #tcp_nopush     on;

              keepalive_timeout  65;

              gzip  on;
              gzip_comp_level 6;
              gzip_proxied any;
              gzip_vary on;
              gzip_types  text/plain text/css application/x-javascript;
              gzip_disable "MSIE [1-6]\.(?!.*SV1)";

              include /etc/nginx/conf.d/*.conf;
          }