- name: Delete a namespace
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ client }}-system"

- name: Delete a k8s volume
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ client }}-nfs"