- name: Delete a namespace
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ns }}"

- name: Delete a k8s volume
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ ns }}-nfs"

- name: Delete website files
  file:
    path: "{{ site_path}}"
    state: absent
  delegate_to: "{{ server_nfs }}"

- name: Update exportfs
  ansible.builtin.lineinfile:
    path: /etc/exports
    search_string: "/data/{{ client }}"
    state: absent
  delegate_to: "{{ server_nfs }}"

- name: Update exportfs commande
  shell: exportfs -a
  delegate_to: "{{ server_nfs }}"