- name: Delete a namespace
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ client }}"-system

- name: Delete a k8s volume
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ client }}-nfs"

- name: Delete website files
  file:
    path: "{{ site_path_test_delete}}"
    state: absent
  delegate_to: "{{ server_nfs }}"

- name: Update exportfs
  ansible.builtin.lineinfile:
    path: /etc/exportfs
    search_string: "/data/{{ client }}"
    state: absent
  command: exportfs -a
  delegate_to: "{{ server_nfs }}"