- name: Delete a namespace
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ client }}"

- name: Delete a k8s volume
  k8s:
    kubeconfig: /root/.kube/config
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ ns }}-nfs"

- name: Delete website files
  file:
    path: "{{ site_path }}"
    state: absent
  delegate_to: "{{ server_nfs }}"